# Generated by Django 6.0.3 on 2026-04-04 05:02

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "land_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=32, unique=True
                    ),
                ),
                ("survey_number", models.CharField(max_length=64)),
                ("hissa", models.CharField(blank=True, max_length=64)),
                (
                    "extent_acres",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "extent_guntas",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "extent_sqft",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("AGRICULTURAL", "Agricultural"),
                            ("CONVERTED", "Converted"),
                            ("APPROVED_SITE", "Approved Site"),
                        ],
                        default="AGRICULTURAL",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("UNDER_NEGOTIATION", "Under Negotiation"),
                            ("COMMITTED", "Committed"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
                (
                    "investment_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "investment_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_land_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="land_files",
                        to="geography.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Land File",
                "verbose_name_plural": "Land Files",
                "ordering": ["-created_at"],
            },
        ),
    ]
