# Generated by Django 6.0.3 on 2026-04-05 09:34

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        ("land", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Officer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("DC", "District Commissioner"),
                            ("AC", "Assistant Commissioner"),
                            ("TAHSILDAR", "Tahsildar"),
                            ("DEPUTY_TAHSILDAR", "Deputy Tahsildar"),
                            ("VA", "Village Accountant"),
                            ("RI", "Revenue Inspector"),
                            ("ADLR", "Assistant Director of Land Records"),
                            ("DDLR", "Deputy Director of Land Records"),
                        ],
                        default="VA",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_officers",
                        to="geography.district",
                    ),
                ),
                (
                    "internal_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_officer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taluk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_officers",
                        to="geography.taluk",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Officer",
                "verbose_name_plural": "Revenue Officers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GovernmentWorkflow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MUTATION", "Mutation"),
                            ("PHODI", "Phodi"),
                            ("TIPPANI", "Tippani"),
                            ("RTC_CORRECTION", "RTC Correction"),
                            ("CONVERSION", "Conversion"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("APPLIED", "Applied"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("ON_HOLD", "On hold"),
                        ],
                        default="NOT_STARTED",
                        max_length=64,
                    ),
                ),
                ("applied_on", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="government_workflows",
                        to="land.landfile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "officer_handling",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflows",
                        to="revenue.officer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Government workflow",
                "verbose_name_plural": "Government workflows",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("land", "kind"),
                        name="unique_active_workflow_per_land",
                    )
                ],
            },
        ),
    ]
