# Generated by Django 6.0.3 on 2026-04-05 06:24

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0001_initial"),
        ("land", "0001_initial"),
        ("revenue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Officer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("DC", "District Commissioner"),
                            ("AC", "Assistant Commissioner"),
                            ("TAHSILDAR", "Tahsildar"),
                            ("DEPUTY_TAHSILDAR", "Deputy Tahsildar"),
                            ("VA", "Village Accountant"),
                            ("RI", "Revenue Inspector"),
                            ("ADLR", "Assistant Director of Land Records"),
                            ("DDLR", "Deputy Director of Land Records"),
                        ],
                        default="VA",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Officer",
                "verbose_name_plural": "Revenue Officers",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="governmentworkflow",
            name="revenue_govworkflow_unique_land_kind_active",
        ),
        migrations.AlterField(
            model_name="governmentworkflow",
            name="kind",
            field=models.CharField(
                choices=[
                    ("MUTATION", "Mutation"),
                    ("PHODI", "Phodi"),
                    ("TIPPANI", "Tippani"),
                    ("RTC_CORRECTION", "RTC Correction"),
                    ("CONVERSION", "Conversion"),
                ],
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="officer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="officer",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="officer",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenue_officers",
                to="geography.district",
            ),
        ),
        migrations.AddField(
            model_name="officer",
            name="internal_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenue_officer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="officer",
            name="taluk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenue_officers",
                to="geography.taluk",
            ),
        ),
        migrations.AddField(
            model_name="officer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="governmentworkflow",
            name="officer_handling",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflows",
                to="revenue.officer",
            ),
        ),
        migrations.AddConstraint(
            model_name="governmentworkflow",
            constraint=models.UniqueConstraint(
                fields=("land", "kind"), name="unique_active_workflow_per_land"
            ),
        ),
    ]
