# Generated by Django 6.0.3 on 2026-04-04 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geography", "0001_initial"),
        ("land", "0001_initial"),
        ("revenue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="governmentworkflow",
            name="applied_on",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="governmentworkflow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="governmentworkflow",
            name="kind",
            field=models.CharField(
                choices=[
                    ("MUTATION", "Mutation"),
                    ("PHODI", "Phodi"),
                    ("TIPPANI", "Tippani"),
                    ("RTC_CORRECTION", "RTC Correction"),
                    ("CONVERSION", "Conversion"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="governmentworkflow",
            name="land",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="government_workflows",
                to="land.landfile",
            ),
        ),
        migrations.AlterField(
            model_name="governmentworkflow",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Officer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("DC", "District Commissioner"),
                            ("AC", "Assistant Commissioner"),
                            ("TAHSILDAR", "Tahsildar"),
                            ("DEPUTY_TAHSILDAR", "Deputy Tahsildar"),
                            ("VA", "Village Accountant"),
                            ("RI", "Revenue Inspector"),
                            ("ADLR", "Assistant Director of Land Records"),
                            ("DDLR", "Deputy Director of Land Records"),
                        ],
                        default="VA",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geography.district",
                    ),
                ),
                (
                    "internal_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_officer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taluk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geography.taluk",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="governmentworkflow",
            name="officer_handling",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflows",
                to="revenue.officer",
            ),
        ),
    ]
