# Generated by Django 6.0.3 on 2026-04-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("state", models.CharField(default="Karnataka", max_length=64)),
            ],
            options={
                "verbose_name_plural": "districts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Taluk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taluks",
                        to="geography.district",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "taluks",
                "ordering": ["name"],
                "unique_together": {("name", "district")},
            },
        ),
        migrations.CreateModel(
            name="Hobli",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "taluk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hoblis",
                        to="geography.taluk",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "hoblis",
                "ordering": ["name"],
                "unique_together": {("name", "taluk")},
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "hobli",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="villages",
                        to="geography.hobli",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "villages",
                "ordering": ["name"],
                "unique_together": {("name", "hobli")},
            },
        ),
    ]
