# Generated by Django 6.0.3 on 2026-04-04 05:02

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("s3_key", models.CharField(blank=True, max_length=1024)),
                ("original_filename", models.CharField(blank=True, max_length=512)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_versions_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document version",
                "verbose_name_plural": "Document versions",
                "ordering": ["checklist_item", "-version_number"],
            },
        ),
        migrations.CreateModel(
            name="LandDocumentChecklistItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[
                            ("RTC", "RTC"),
                            ("EC", "Encumbrance certificate"),
                            ("PHODI_SKETCH", "Phodi sketch"),
                            ("TIPPANI", "Tippani"),
                            ("GRANT_ORDER", "Grant order"),
                            ("COURT_CERTIFIED_COPY", "Court certified copy"),
                            ("OTHER", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "checklist_status",
                    models.CharField(
                        choices=[
                            ("CERTIFIED_OBTAINED", "Certified obtained"),
                            ("APPLIED_PENDING", "Applied & pending"),
                            ("NOT_APPLICABLE", "Not applicable"),
                        ],
                        default="APPLIED_PENDING",
                        max_length=32,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Land document checklist item",
                "verbose_name_plural": "Land document checklist items",
                "ordering": ["document_kind"],
            },
        ),
    ]
