# Generated by Django 6.0.3 on 2026-04-04 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("land", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="landdocumentchecklistitem",
            name="land",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_checklist_items",
                to="land.landfile",
            ),
        ),
        migrations.AddField(
            model_name="landdocumentchecklistitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="checklist_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="documents.landdocumentchecklistitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="landdocumentchecklistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("land", "document_kind"),
                name="documents_checklist_unique_land_kind_active",
            ),
        ),
    ]
