# Generated by Django 6.0.3 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalcase",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="legalcase",
            name="case_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OS", "OS"),
                    ("MFA", "MFA"),
                    ("WP", "WP"),
                    ("CRP", "CRP"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="legalcase",
            name="court_jurisdiction",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="legalcase",
            name="party_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PLAINTIFF", "Plaintiff"),
                    ("DEFENDANT", "Defendant"),
                    ("PETITIONER", "Petitioner"),
                    ("RESPONDENT", "Respondent"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="legalcase",
            name="current_stage",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="legalcase",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
